version: "3"

services:
  blog-postgres:
    image: postgres:11.3-alpine
    container_name: blog-postgres
    environment:
      - POSTGRES_DATABASE=blog_api
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      # copy startup script to /docker-entrypoint-initdb.d directory
      # used for initiating our database
      - ./scripts/postgresql/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh

      # persist data so that it doesn't get deleted after container restarts
      - postgres-data:/data/db
    
    restart: on-failure

volumes:
  postgres-data:
